### ISSUE TITLE
Make the certificate alias configurable with fallback to "certificate"

### ISSUE THREAD

**Issue by HenningL** [xdev-software/bzst-dip-java-client#59]
### Checklist

- [X] I made sure that there are *no existing issues* - [open](https://github.com/xdev-software/bzst-dip-java-client/issues) or [closed](https://github.com/xdev-software/bzst-dip-java-client/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request/enhancement.

### Description

By now the certificate alias is hardcoded as "certificate" in SigningUtil. Would be nice if its configurable and fallback as it is if not configured.
![image](https://github.com/user-attachments/assets/f7b9fc6f-268d-43cf-b6a5-1c2a5b8fe22d)

**Comment by JohannesRabauer** [comment]
Hi Henning,
thank you for your enhancement idea!
We tried to implement your request on branch [changeable-keystore-entry-name](https://github.com/xdev-software/bzst-dip-java-client/tree/changeable-keystore-entry-name).
Could you please check if this is what you wanted and if this works? Usage see https://github.com/xdev-software/bzst-dip-java-client/blob/changeable-keystore-entry-name/CHANGELOG.md#102

If it works we would create a new release with this feature included.

**Comment by HenningL** [comment]
Hi Johannes. I checked the changes and saw it is configurable now. I couldnt find the place for the fallback to "certificate", just to keep it backwards compatible if the property is not set. if you think, it becoming a mandatory property to be configured, i am also fine with it.

**Comment by JohannesRabauer** [comment]
In bzst-dip-java-client/src/main/java/software/xdev/bzst/dip/client/model/configuration/BzstDipConfigurationBuilder.java the following lines set the default alias "certificate", so the property **is not mandatory**.
```
this.getSetPropertyOrReadFromFile(
				this.keyStorePrivateKeyAlias,
				PropertiesSupplier.PROPERTY_NAME_KEYSTORE_PRIVATE_KEY_ALIAS,
				"certificate"),
```

We'll merge the PR now: https://github.com/xdev-software/bzst-dip-java-client/pull/63
